Repository dedica-team/nivio, pull requests merged in 2020-09, with the labels that each got.

#192 140 websockets frontend
  src/main/app/package.json
  src/main/app/src/App.test.tsx
  src/main/app/src/Components/LandscapeComponent/LandscapeMap/LandscapeMap.scss
  src/main/app/src/Components/LandscapeComponent/LandscapeOverview/LandscapeOverview.tsx
  src/main/app/src/Components/LayoutComponent/Layout.tsx
  src/main/app/src/Components/NotificationComponent/Notification.scss
  src/main/app/src/Components/NotificationComponent/Notification.tsx
  src/main/app/src/interfaces.ts
  src/main/app/yarn.lock
  src/main/java/de/bonndan/nivio/AsyncEventsConfig.java
  src/main/java/de/bonndan/nivio/notification/MessagingService.java
  src/main/java/de/bonndan/nivio/notification/WebSocketConfig.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGDocument.java
  src/main/resources/static/css/svg.css
Labels: enhancement, javascript

#269 Remove map button if landscape is unknown
  src/main/app/src/Components/NotificationComponent/Notification.test.tsx
  src/main/app/src/Components/NotificationComponent/Notification.tsx
  src/main/app/src/Components/NotificationComponent/NotificationLayout.tsx
  src/main/app/src/interfaces.ts
Labels: bug, javascript

#270 Dynamic Manual
  src/main/app/README.md
  src/main/app/package.json
  src/main/app/src/Components/LandscapeComponent/LandscapeMap/LandscapeMap.tsx
  src/main/app/src/Components/LandscapeComponent/LandscapeOverview/LandscapeOverviewLayout.tsx
  src/main/app/src/Components/ManComponent/Man.test.tsx
  src/main/app/src/Components/ManComponent/Man.tsx
  src/main/app/src/Components/NavigationComponent/Navigation.test.tsx
  src/main/app/src/Components/NavigationComponent/Navigation.tsx
  src/main/app/src/utils/API/APIConfig.ts
  src/main/app/src/utils/API/BasePath.test.tsx
  src/main/app/src/utils/API/BasePath.ts
  src/main/app/yarn.lock
Labels: javascript

#240 Readme for docker, dependency update, JDK13 support
  .github/workflows/ci.yml
  docs/source/install.rst
  nivio-demo/docker-compose.yml
  pom.xml
  readme.md
  src/main/java/de/bonndan/nivio/input/ItemDescriptions.java
  src/main/java/de/bonndan/nivio/model/ItemIndex.java
  src/main/java/de/bonndan/nivio/model/LandscapeItems.java
  src/test/docker-compose.yml
Labels: bug, cleanup, documentation, java

#271 Update readme screenshots
  docs/graph.png
  docs/gui.png
  docs/inout.png
Labels: cleanup
