Repository dedica-team/nivio, pull requests merged in 2020-08, with the labels that each got.

#225 [#224] fix for group names
  src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupArea.java
  src/test/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaTest.java
  src/test/resources/example/example_csv_debug.svg
  src/test/resources/example/example_env_debug.svg
  src/test/resources/example/example_four_groups_debug.svg
  src/test/resources/example/inout_debug.svg
  src/test/resources/example/large_debug.svg
  src/test/resources/example/model_debug.svg
Labels: cleanup

#227 groups surrounded
  src/main/java/de/bonndan/nivio/output/map/hex/Hex.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGDocument.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupArea.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaFactory.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaOutlineFactory.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGHex.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGRenderer.java
  src/test/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaFactoryTest.java
  src/test/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaOutlineFactoryTest.java
  src/test/java/de/bonndan/nivio/output/map/svg/SVGHexTest.java
  src/test/java/de/bonndan/nivio/output/map/svg/SVGRendererTest.java
  src/test/resources/example/example_csv_debug.svg
  src/test/resources/example/example_env_debug.svg
  src/test/resources/example/example_four_groups_debug.svg
  src/test/resources/example/inout_debug.svg
  src/test/resources/example/large_debug.svg
  src/test/resources/example/model_debug.svg
Labels: enhancement, java

#230 bezier outlines around groups
  src/main/java/de/bonndan/nivio/output/map/hex/Hex.java
  src/main/java/de/bonndan/nivio/output/map/hex/HexFactory.java
  src/main/java/de/bonndan/nivio/output/map/svg/HexPath.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGDocument.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaOutlineFactory.java
  src/main/java/de/bonndan/nivio/output/map/svg/SVGRelation.java
  src/test/resources/example/example_csv_debug.svg
  src/test/resources/example/example_env_debug.svg
  src/test/resources/example/example_four_groups_debug.svg
  src/test/resources/example/inout_debug.svg
  src/test/resources/example/large_debug.svg
  src/test/resources/example/model_debug.svg
Labels: cleanup, enhancement

#235 Omit dependency download logs during Maven test run
  .github/workflows/ci.yml
Labels: enhancement
